version: "3"
services: 
  api:
    depends_on: 
      - db    
    build: ./backend
    volumes: 
      - ./backend:/workspace
    ports: 
      - 3000:3000
    networks: 
      - repository-research
    env_file: 
      - .env
    environment:
        WORKING_DIR: "/workspace"
    command: > 
      /bin/ash -c 
        "chmod +x wait.sh \
        && ./wait.sh db ${DB_PORT}"
  db:
    image: mysql:8.0.19
    restart: always
    environment: 
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_HOST: localhost
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
    ports: 
      - ${DB_PORT}:${DB_PORT}
    networks: 
      - repository-research
    volumes: 
      - ./db/data:/var/lib/mysql
      - ./db/init.d:/docker-entrypoint-initdb.d
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/log:/var/log/mysql
    command: mysqld

networks: 
  repository-research:
