version: "3"
services: 
  api:
    depends_on: 
      - db    
    build: ./backend
    volumes: 
      - ./backend:/workspace
    container_name: 'repository-research-api'
    expose:
      - 3000
    env_file: 
      - .env
    environment:
      WORKING_DIR: "/workspace"
    command: > 
      /bin/ash -c 
        "chmod +x wait.sh \
        && ./wait.sh db ${DB_PORT}"
  db:
    image: mysql:8.0.19
    restart: always
    container_name: 'repository-research-db'
    environment: 
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_HOST: localhost
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
    expose:
      - ${DB_PORT}
    volumes: 
      - ./db/data:/var/lib/mysql
      - ./db/init.d:/docker-entrypoint-initdb.d
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/log:/var/log/mysql
    command: mysqld
  front:
    build: ./front
    container_name: 'repository-research-front'
    expose:
      - 3002
    volumes:
      - ./front:/workspace
    environment:
      PORT: 3002
      HOST: 0.0.0.0
  reverse-proxy:
    depends_on: 
      - api
      - front
    image: nginx
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    restart: always
